### ISSUE TITLE
Sampling Rate Inconsistency?

### ISSUE THREAD

**Issue by DutchGFX** [pyrtlsdr/pyrtlsdr#87]
Hey all, I'll cut to the chase

I try to sample for a certain period of time, but it always samples for roughly 3-5 longer, yet returns the correct number of samples. I wrote a simple script that pretty much just executes this code, yet nomatter if seg_length is 1s or 50ms or 300ms or anything, it records for anywhere between 3-5x that length

```
fs = 2.4e6
sdr.rs = fs
sdr.gain = 50
sdr.fc = 100e6

seg_length = 1` 
num_samples = int(fs*seg_length)

a = time()
data = read_samples(num_samples)
b = time()

print(b-a)
```

I have omitted the include statements for easier reading. Any ideas? My SDR is not with me so I'll have to wait until monday to test, but any help is much appreciated! Thanks so much

**Comment by nocarryr** [comment]
While I would never rely too heavily on timing accuracy between function calls within python, 3-5 times the expected duration does seem pretty drastic.

Do you have numpy installed in your environment?  My first guess would be the calculations done after the raw samples have been read in `[packed_bytes_to_iq]`(https://github.com/roger-/pyrtlsdr/blob/4e877f9e4a1dbe04a30e5dfdb0b0ed7bb5026b2d/rtlsdr/rtlsdr.py#L501-L520)

I would recommend doing the same test as above, but using `read_bytes(num_samples)` instead of `read_samples(num_samples)` just to see if it has an impact on the timing.

**Comment by DutchGFX** [comment]
I do have numpy installed. I would think that  the calculations would be quick as no other computations I do take more than a few ms. I can't imagine computations taking 5+ seconds. What does read_bytes return? 

Thanks for the quick response. I just realized I've been using sdr.rs but the example has sdr.sample_rate... did I mess that up?

**Comment by nocarryr** [comment]
`read_bytes` returns a `ctypes.Array` with the "real" (In-phase) and "imaginary" (Quadrature) components interleaved.  It is not memory-safe since the buffer is reused between calls, but it's the lowest-overhead call possible with pyrtlsdr.

`sdr.rs` can be used interchangeably with `sdr.sample_rate`

**Comment by DutchGFX** [comment]
And read_samples returns a numpy array? Can i, myself, store the cTypes array into a numpy array during post processing?

**Comment by nocarryr** [comment]
Yes, you could use something like:
```python
raw_data = sdr.read_bytes(num_samples*2)  # We need 2 bytes for every sample (real+imag)
copied_data = np.frombuffer(raw_data, dtype=np.uint8) # I *think* np.uint8 is the correct dtype to use
```
This doesn't handle any conversion at all though.  It's a direct copy of the values, not an array of complex numbers like what's returned from `read_samples`

**Comment by DutchGFX** [comment]
I could go inside rtlsdr.py (I have to find it...) and add the timing to the read_bytes() command to see if that's timed properly or to see if maybe the issue isn't the computation. 

What do you mean direct copy of the data? Is the data not complex IQ samples?

**Comment by nocarryr** [comment]
The data returned from `read_bytes` is a C array of unsigned int values (0-255) as they are received from the underlying [librtlsdr](https://github.com/librtlsdr/librtlsdr) library.  The components of the complex-valued IQ data are interleaved in the 1-dimensional array with the "real" components in even-numbered indexes and "imag" in odd-numbered indexes.

Construction of the complex-valued numpy array happens in `packed_bytes_to_iq`:
https://github.com/roger-/pyrtlsdr/blob/4e877f9e4a1dbe04a30e5dfdb0b0ed7bb5026b2d/rtlsdr/rtlsdr.py#L512-L515

Instead of editing rtlsdr.py, you could do this and have the same result:
```python
num_samples = int(fs*seg_length)
num_bytes = num_samples * 2

a = time()
raw_data = sdr.read_bytes(num_bytes)
b = time()
data = sdr.packed_bytes_to_iq(raw_data)
c = time()

print('Read bytes duration: ', b-a)
print('Process samples duration: ', c-b)
print('Total duration: ', c-a)
```
That would achieve the same result as `read_samples`, only allowing you to catch the individual steps in the process.

**Comment by DutchGFX** [comment]
Nvm, I see what you mean. I'll test using read_bytes to see if I can get the timing to be more reasonable. I'll let you know

Thanks so much for the help

**Comment by DutchGFX** [comment]
Perfect. Thanks so much. I really truly appreciate the assistance. I'm not using it for mission-critical timing, but I would like the error to be a few ms at most. I'm generally recording 10ms clips, so if the duration was below 15ms that'd be fine. 

Maybe I'll do the processing post observation. I take a bunch of short observations and store them in files, then merge at the end. Maybe I can minimize the conversions in real time and do it all as post processing.

**Comment by patrickcgray** [comment]
@DutchGFX were you able to find why it was taking much longer to record than it should have? I think I'm having the same issues, taking around sampling at `2.4e6` and taking `2.4e6 * 2` samples so it should take 2 seconds, yet it consistently takes more like 6 seconds. I'm curious if you have any solution.

**Comment by hemanti0503** [comment]
I'm having the same issue. Any news on this one?

**Comment by DutchGFX** [comment]
Sorry, I never responded to this. The issue is the processing, not the sampling. The function "packed_bytes_to_iq()" or whatever it's called is the bottleneck. We fixed the issue by doing

```
    samples = sdr.read_bytes(num_samples_per_recording*2)
    complex_samples = (np.frombuffer(samples, dtype=np.uint8) - 127.5)/255.0
    complex_samples = complex_samples.astype(np.float32).view(np.complex64)
```

That reduced the conversion to a reasonably small time

**Comment by nocarryr** [comment]
That's good to hear. Also not surprising that the `np.frombuffer()` method is more efficient than using native slicing. Would you be willing to create a pull request with those changes?

**Comment by nocarryr** [comment]
@DutchGFX I created a gist to profile various manipulation methods and from what I've seen on my machine, the method based off of your example is the most efficient:
```python
# raw_data is the output from sdr.read_bytes()
data = np.frombuffer(raw_data, dtype=np.uint8)
data = (data - 127.5) / 127.5
iq = np.empty(data.size // 2, dtype=np.complex128)
iq.real, iq.imag = data[::2], data[1::2]
```

Take a look at [the gist](https://gist.github.com/nocarryr/4e55c117daf1ba57ceff1dcd2e5cdaab) for the profile results.

This may finally close #15

**Comment by hemanti0503** [comment]
@nocarryr This looks really nice, impressive profiling results. Thank you! :-) Is there any chance the code will be merged to the master branch and be released soon?

May I ask why in the `frombuffer_int_proc(raw_data)` we don't need the `iq -= (1 + 1j)` from the comples versions? I haven't bee coding python for long and I cannot make sense out of that yet.

**Comment by hemanti0503** [comment]
@nocarryr Thank you for pointing that out! Totally overlooked that.

What is the normal process after a PR? Several people should look at it, test it and then will be given green light to merge? By the time it is merged, how do is it decided if and when a new release will be made?

**Comment by nocarryr** [comment]
@hemanti0503 for this project, there are no specific guidelines for the review/merge process or for the release cycle.

Pull requests that don't have any foreseeable issues with the core parts of the library are usually merged pretty quickly (as long as the tests pass).  Releases are made sort of "whenever".  If there was a recent feature addition, bug fix or if it's something someone really, really wants up on PyPI, then I'll bump the version and make a release.

Since this changes the core **and** alters the output from `sdr.read_samples` (even though it's only off by a very small amount), I'd like for others to weigh in.

I think the discussion for the changes in question though should be moved to PR #88 instead of here though.

**Comment by nocarryr** [comment]
@hemanti0503 @DutchGFX the updated version is now available on PyPI

**Comment by hemanti0503** [comment]
Wow! Thank you so much, @nocarryr and @DutchGFX! :)
